apiVersion: v1
kind: Service
metadata:
  name: converter-service
spec:
  selector:
    app: converter-service
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001
  type: ClusterIP # Internal communication within the cluster
