apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 0000
      nodePort: 30002
  type: NodePort
 
